https:
  port: "8082"
  host: "localhost"
  keystore: 
    path: "keystores/keystore.jks"
    type:  "JKS"
    password: "password"
  base:
    path: ""

interface:
  userName: "andre"
  passWord: "bandre"
  html:
    path: 
      login-form:  "/interface/getLoginForm.html"
      values-form: "/interface/getOSValuesForm.html"
      values-response: "/interface/getOSValuesResponse.html"
      payload-response: "/interface/getOSPayloadResponse.html"

  session:
    ttlMinutes: "15"
    ttlInterval: "1"
    maxEntries: "500"
    
    path: 
      generic: "/ui/interface/*"
      login-form:   "/interface/login"
      login-response:  "/interface/getLoginResponse"
      logout: "/interface/logout"
      get-values-form: "/interface/getOSValuesForm"
      get-values-response:  "/interface/getValues"
      get-os-payload: "/interface/getOSPayload"
      
api:
  listener:
    path:
      get-os-values: "/api/getOSValues"
      set-os-values: "/api/setOSValue"
      gen-os-values: "/api/genOSValues"
      clear-os-values: "/api/clearOSValues"
      
deckCommerce:
  objectStore:
    maxEntries:  "100000"
    ttlMinutes:  ""
    
      